prof_site/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('person/<slug:slug>/', views.PersonDetailView.as_view(), name='person_detail'),
    path('api/vita/', views.vita_view, name='vita_json'),
]

prof_site/prof_site/urls.py
from django.contrib.gis import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prof_site/blog/models.py
from markdownx.models import MarkdownxField
from django.contrib.gis.db import models
from django.db.models import F
from markdownx.utils import markdownify
from .pandoc import pandocify
from autoslug.settings import slugify as default_slugify
from autoslug import AutoSlugField
from django.utils.functional import cached_property
from django.core.serializers import serialize
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToCover, Adjust, ColorOverlay, SmartResize
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from .zotero_update import zotero_pull, zotero_version
from django.conf import settings
from .geocode import geocode_address
import os

class VersionClass(models.Model):
    """
    Defines a default class with created at/modified at fields.
    All the below models inherit this class.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Institution(VersionClass):
    name = models.CharField(
        help_text="Name of the institution.",
        max_length=150, 
        null=False, 
        blank=False
    )
    address = models.CharField(
        help_text = "Address of the institution.",
        max_length=200, 
        null=False, 
        blank=True, 
        default=''
    )
    room = models.CharField(
        help_text = "Room at which the institution can be reached.",
        max_length=20, 
        null=False, 
        blank=True, 
        default=''
    )
    city = models.CharField(
        help_text = "City in which institution is located.",
        max_length=100
    )
    state = models.CharField(
        help_text = "State in which institution is located.",
        max_length=100
    )
    postal = models.CharField(
        help_text = "Postcode in which institution is located.",
        max_length=20,
        blank=True,
        default=''
    )
    country = models.CharField(
        help_text = "Country in which institution is located.",
        max_length=100
    )
    website = models.URLField(
        help_text = "Institution's website.",
        null=False, 
        blank=True, 
        default=''
    )
    parent = models.ForeignKey(
        'self', 
        help_text = "Parent institution of institution (E.g., 'MIT' is the parent of 'DUSP').",
        null=True, 
        blank=True, 
        on_delete=models.SET_NULL
    )
    location = models.PointField(
        help_text = "Approximate location of institution.",
        null=True,
        blank=True
    )
    def save(self, *args, **kwargs):
        """
        Overwrite save method to update main bibliography when model is saved.
        """
        if self.location:
            pass
        else:
            add_array = [self.address, self.city, self.state, self.postal, self.country]
            query = ','.join(filter(None, add_array))
            self.location = geocode_address(query)
        super(Institution, self).save(*args, **kwargs)
    class Meta:
        verbose_name = "Institution"
        verbose_name_plural = "Institutions"

    def __str__(self):
        return self.name

class Award(VersionClass):
    """
    Describes awards and honors given to persons included
    in Persons.
    """
    start = models.DateField(
        help_text = "Start of the award term.",
        null = False, 
        blank = False
        )
    end = models.DateField(
        help_text = "End of the award term.",
        null = True, 
        blank = True
        )
    name = models.CharField(
        help_text = "Name of the award.",
        max_length = 200, 
        null = False, 
        blank = False
        )
    KINDS = [
        ('A', 'Awards and Honors'),
        ('F', 'Funding'),
        ('', 'None')
    ]
    kind = models.CharField(
        help_text = "Make the distinction between funding and awards/honors.",
        max_length = 3,
        choices = KINDS,
        null = False,
        blank = True,
        default = ''
    )
    amount = models.IntegerField(
        help_text = "The amount of money awarded, in its given currency (see next field).",
        null=True, 
        blank=True
    )
    CURRENCY = [
        ('CAD', 'Canadian Dollar'),
        ('USD', 'United States Dollar'),
    ]
    currency = models.CharField(
        help_text = "The currency in which the award/grant is given.",
        max_length = 3,
        choices = CURRENCY,
        null = False,
        blank = True,
        default = 'USD'
    )
    pi_awardee = models.ForeignKey(
        'Person', 
        help_text = "P.I. or awardee.",
        null = True, 
        on_delete = models.SET_NULL
    )
    grantees = models.ManyToManyField(
        Institution,
        help_text = "All institutions who received the award/grant.", 
        blank=True
    )
    grantor = models.ForeignKey(
        Institution, 
        help_text = "All institutions who received the award/grant.",
        null = True, 
        on_delete = models.SET_NULL, 
        related_name='grantor'
    )
    show = models.BooleanField(
        help_text = "Indicates the visibility of this award on the frontend.",
        null=False, 
        default=True
    )

    class Meta:
        verbose_name = "Award"
        verbose_name_plural = "Awards"

    def __str__(self):
        return self.name

class Person(VersionClass):
    """
    Model describing a person, their (ugh) credentials, social, etc.
    """
    first = models.CharField(
        help_text = "Person's given name.",
        max_length=50
    )
    middle = models.CharField(
        help_text = "Person's middle name(s).",
        max_length=50, 
        blank=True, 
        default=''
    )
    last = models.CharField(
        help_text = "Person's last name(s).",
        max_length=50
    )
    email = models.EmailField(
        help_text = """Personal email. Useful in the absence
        of an affiliated email.""",
        blank=True, 
        default=''
    )
    GENDERS = [
        ('M', 'He/him/his'),
        ('W', 'She/her/hers'),
        ('N', 'He/him/his or They/them/theirs'),
        ('H', 'She/her/hers or They/them/theirs'),
        ('T', 'They/them/theirs'),
    ]
    pronouns = models.CharField(
        help_text = "Preferred pronouns.",
        max_length=1,
        choices=GENDERS,
        default='T',
    )
    CREDS = [
        ('MCP', 'M. City Planning'),
        ('PhD', 'Ph.D.'),
        ('MUP', 'M. Urban Planning'),
        ('MURP', 'M. Urban and Regional Planning'),
        ('MFA', 'M. Fine Arts'),
        ('MLA', 'M. Landscape Architecture'),
        ('MArch', 'M. Architecture'),
        ('MBA', 'M. Business Administration'),
        ('MPA', 'M. Public Administration'),
        ('MDes', 'M. Design Studies'),
        ('DDes', 'D.Des.'),
        ('', 'None'),
    ]
    cred = models.CharField(
        help_text = "Display credential.",
        max_length = 5,
        choices = CREDS,
        blank=True,
        default=''
    )
    bio = MarkdownxField(
        help_text = "Person's short biography.",
        blank=True
    )
    website = models.URLField(
        help_text = "Person's personal website (independent their affiliations).",
        null=False, 
        blank=True, 
        default=''
    ) 
    photo = models.ImageField(
        help_text = "Photo/headshot.",
        null=True, 
        blank=True, 
        upload_to = 'authors/images/%Y/%m/%d'
    )
    orcid = models.CharField(
        help_text = "Person's ORCID.",
        max_length=19, 
        blank=True
    )
    pgp = models.CharField(
        help_text = "Person's PGP key.",
        max_length=50, 
        blank=True
    )
    twitter = models.CharField(
        help_text = "Person's Twitter handle.",
        max_length=50, 
        blank=True
    )
    gitlab = models.CharField(
        help_text = "Person's Gitlab handle.",
        max_length=25, 
        blank=True, 
        default=''
    )
    github = models.CharField(
        help_text = "Person's Github handle.",
        max_length=25, 
        blank=True, 
        default=''
    )
    zotero = models.CharField(
        help_text = "Person's Zotero handle.",
        max_length=25, 
        blank=True, default=''
    )
    linkedin = models.CharField(
        help_text = "Person's LinkedIn handle.",
        max_length=25, 
        blank=True, 
        default=''
    )
    photo_gray = ImageSpecField(source='photo',
        processors=[
            Adjust(color=0,contrast=1.5, brightness=1.5),
            ColorOverlay(color = "#CC003E", overlay_opacity = 0.6 )
        ],
        format='PNG'
    )
    photo_thumb = ImageSpecField(
        source='photo',
        processors=[ResizeToFill(100, 100)],
        format='PNG'
    )
    slug = AutoSlugField(
        populate_from='full_name',
        default=None, 
        always_update=False, 
        max_length=150
    )
    affil = models.ManyToManyField(
        Institution, 
        help_text = "List of person's current and historical affiliations.",
        through='Affiliation'
    )
    vita = models.FileField(
        help_text = "Current curriculum vita.",
        upload_to='authors/vitae/', 
        blank=True, 
        default=''
    )
    page = models.BooleanField(
        help_text = "Does this person have their own detail page?",
        default=False
    )
    @property
    def formatted_markdown(self):
        """
        Formats bio markdown.
        """
        return markdownify(self.bio)

    @property
    def current_affiliations(self):
        """
        Lists current affiliations (i.e., those without a specified end date)
        with primary affiliations first.
        """
        return self.affiliation_set.filter(end = None, show=True, kind='Aff').order_by(F('primary').desc(nulls_last=True),F('start').desc())

    @property
    def current_appointments(self): 

prof_site/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize
from el_pagination.decorators import page_template
from django.db.models import F
from .models import SiteWideSetting, Post, Person, UrbanArea, Land, Event, Education, Affiliation, Award
from django.http import HttpResponse, JsonResponse
from .serializers import EducationSerializer, InstitutionSerializer, MainPersonSerializer, AffiliationSerializer, AwardSerializer

from datetime import datetime, timedelta, time
from el_pagination.views import AjaxListView

def vita_view(request):
    try:
        main_person_id = SiteWideSetting.objects.all()[0].main_person.id
        main_person = Person.objects.filter(
                id=main_person_id
            ).all()
        education = Education.objects.filter(
                show=True,
                person__id=main_person_id
            ).order_by(
                F('end').desc(nulls_first=True)
            )
        appointments = Affiliation.objects.filter(
                person__id=main_person_id,
                show=True,
                kind='App',
            ).order_by(
                F('primary').desc(),
                F('end').desc(nulls_first=True),
            )
        affiliations = Affiliation.objects.filter(
                person__id=main_person_id,
                show=True,
                kind='Aff',
                end=None
            ).order_by(
                F('end').desc(nulls_first=True)
            )
        funding = Award.objects.filter(
                pi_awardee__id=main_person_id,
                show=True,
                kind='F'
            ).order_by(F('start').desc(nulls_first=True))
        awards = Award.objects.filter(
                pi_awardee__id=main_person_id,
                show=True,
                kind='A'
            ).order_by(F('start').desc(nulls_first=True))
        advisees = Education.objects.filter(
                committee__id__exact=main_person_id
            ).order_by(
                F('end').desc(nulls_first=True)
            )
    except Education.DoesNotExist or Person.DoesNotExist or Affiliation.DoesNotExist or Award.DoesNotExist:
        return HttpResponse(status=404)
    
    if request.method == 'GET':
        main_s = MainPersonSerializer(main_person, many=True)
        appointments_s = AffiliationSerializer(appointments, many=True)
        education_s = EducationSerializer(education, many=True)
        affiliations_s = AffiliationSerializer(affiliations, many=True)
        funding_s = AwardSerializer(funding, many=True)
        awards_s = AwardSerializer(awards, many=True)
        advisees_s = EducationSerializer(advisees, many=True)
        return JsonResponse({
            'main': main_s.data[0],
            'appointments': appointments_s.data,
            'education': education_s.data,
            'affiliations': affiliations_s.data,
            'funding': funding_s.data,
            'awards': awards_s.data,
            'advisees': advisees_s.data
            }, safe=False)

class IndexView(AjaxListView):
    context_object_name = 'latest_post_list'
    template_name = 'blog/post_list.html'
    page_template = 'blog/post_list_page.html'

    def get_queryset(self):
        """Return the last ten published posts."""
        return Post.objects.order_by('-display_datetime')[1:]

    def get_context_data(self, **kwargs):
        today = datetime.now().date()
        context = super(IndexView, self).get_context_data(**kwargs)
        context['first'] = Post.objects.order_by('-display_datetime')[0]
        context['events'] = Event.objects.filter(day__gte=today).order_by('day', 'start')
        return context

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post_detail'

class PersonDetailView(generic.DetailView):
    model = Person
    template_name = 'blog/person_detail.html'
    context_object_name = 'person_detail'

prof_site/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static "blog/css/style.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title %}{{ main_author }}{% endblock %}</title>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="/"><h3>{{ main_author }}</h3></a></h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:person_detail' main_author.slug %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ main_author.vita.url }}">Vita</a>
        </li>
      </ul>
    </div>
  </nav>
  <div id="content">
    <div class="container-fluid">
    {% block content %}{% endblock %}
    </div>
  </div>
    <!-- Footer -->
  <footer class="page-footer font-small pt-4">
      <div class="container text-center text-md-left">
      <hr>
        <div class="row foot-list">
          <div class="col-md-6 mt-md-0 mt-3">
            <ul class="list-unstyled">
              <li class="small-text">Built using FOSS, including: (<a href="https://docs.djangoproject.com/en/2.1/ref/contrib/gis/" target="_blank">Geo</a>)<a href="https://www.djangoproject.com/" target="_blank">Django</a>, <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a>/<a href="https://postgis.net/" target="_blank">PostGIS</a>, <a href="https://pypi.org/project/pypandoc/" target="_blank">(Py)</a><a href="https://pandoc.org/" target="_blank">Pandoc</a>, <a href="https://d3js.org/" target="_blank">D3</a>, and <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>.</li>
              <li class="small-text"><a href="https://gitlab.com/ehuntley/prof_site">Source code</a> is made available under <a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GNU General Public License v3.0</a>.</li>
              <li class="small-text">Served on <a href = "https://ubuntu.com/">Ubuntu</a> using <a href="https://gunicorn.org/">Gunicorn</a> and <a href="https://www.nginx.com/">NGINX</a>.</li> 
            </ul>
          </div>
          <div class="col-md-2 offset-md-4 d-none d-md-block">
            <img src="{% static "blog/images/mit-logo.png" %}"/>
          </div>
        </div>
      </div>
      <div class="footer-copyright text-center py-3">
      </div>
  </footer>
</body>
</html>

prof_site/blog/templates/blog/person_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-1 col-sm-12">
      <img class="author-photo" src="{{ person_detail.photo.url }}"/>
    </div>
    <div class="col-md-6">
    <h3>{{ person_detail.full_name }}</h3>
    <ul class="list-unstyled">
      <li><code><a href="mailto:{{ person_detail.email }}">{{ person_detail.email }}</a></code></li>
      {% if person_detail.twitter %}
        <li><code><a href="https://twitter.com/{{person_detail.twitter }}">@{{person_detail.twitter }}</a></code></li>
      {% endif %}
      <li>{{ person_detail.get_pronouns_display }}.<a href="https://uwm.edu/lgbtrc/support/gender-pronouns/">*</a></li>
    </ul>
    <hr>
    {% for a in person_detail.current_appointments %}
      <ul class="list-unstyled">
        {% if a.website %}
          <li><a href="{{ a.website }}"><em>{{ a.title }}</em></a></li>
        {% else %}
          <li><em>{{ a.title }}</em></li>
        {% endif %}
        <li>{% if a.institution.name %}{{ a.institution.name }}{% endif %}
        {% if a.institution.parent %}| {{ a.institution.parent.name }}{% endif %}
        {% if a.institution.parent.parent %}| {{ a.institution.parent.parent.name }}{% endif %}
        {% if a.institution.parent.parent.parent %}| {{ a.institution.parent.parent.parent.name }}{% endif %}
        
        {{ a.institution.inst }}</li>
        <!-- <li>{{ affiliation.institution.loc_geojson }}</li> -->
      </ul>
    {% endfor %}
    <h5>Current Affiliations</h5>
    <hr>
    {% for affiliation in person_detail.current_affiliations %}
      <ul class="list-unstyled">
        {% if affiliation.website %}
          <li><a href="{{ affiliation.website }}"><em>{{ affiliation.title }}</em></a></li>
        {% else %}
          <li><em>{{ affiliation.title }}</em></li>
        {% endif %}
        <li>{% if affiliation.institution.name %}{{ affiliation.institution.name }}{% endif %}
        {% if affiliation.institution.parent %}| {{ affiliation.institution.parent.name }}{% endif %}
        {% if affiliation.institution.parent.parent %}| {{ affiliation.institution.parent.parent.name }}{% endif %}
        {% if affiliation.institution.parent.parent.parent %}| {{ affiliation.institution.parent.parent.parent.name }}{% endif %}
        
        {{ affiliation.institution.inst }}</li>
        <!-- <li>{{ affiliation.institution.loc_geojson }}</li> -->
      </ul>
    {% endfor %}
    <hr>
    {% if person_detail.orcid %}
      <code>orcid: <a href="https://orcid.org/{{ person_detail.orcid }}">{{ person_detail.orcid }}</a></code><br>
    {% endif %}
    {% if person_detail.pgp %}
      <code>pgp: {{ person_detail.pgp }}</code>
    {% endif %}
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1 col-sm-12">
          {% if person_detail.vita %}
            <hr>
            <a href="{{ person_detail.vita.url }}"><button type="button" class="btn btn-primary btn-lg btn-block">Curriculum vita.</button></a>
          {% endif %}
          <p>{{ person_detail.formatted_markdown|safe }}</p>
        </div>
      </div>
    </div>
</div>
{% comment %} <div class="row">
  <div id="author_map" class="col-md-10 offset-md-1 d-none d-md-block">
  </div>
</div> {% endcomment %}
</div>
{% comment %} <script src="https://d3js.org/d3.v5.min.js"></script> {% endcomment %}
{% endblock%}

prof_site/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="row">
    <div class = "jumbotron post-banner" style = "background-image:url({{post_detail.banner_reduced.url}})">
      <div class="container">
        <div class="col-md-10 offset-md-1 col-sm-10 offset-sm-1 post-banner-text">
          <h4>{{ post_detail.date }}</h4>
          <hr>
          <h1 class="display-4">{{ post_detail.title }}</h1>
          <hr>
          <ul class="list-inline">
            {% for author in post_detail.authors.all %}
            <li class="list-inline-item">
              {% if author.page %}
                <a href="{% url 'blog:person_detail' author.slug %}">{{ author.full_name }}</a>
              {% else %}
                {{ author.full_name }}
              {% endif %}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class = "row">
        <div class="col-md-7 offset-md-1">
          {% if post_detail.attach %}
            <a href="{{ post_detail.attach.url }}"><button type="button" class="btn btn-primary btn-lg btn-block">Download Content.</button></a>
            <hr>
          {% endif %}
          {{ post_detail.pandoc_process|safe }}
        </div>
        <div class="col-md-3 d-none d-md-block">
          {% for author in post_detail.authors.all %}
            {% if author.page %}
              <img class="author-photo" src="{{ author.photo.url }}"/><br>
              <ul class="list-unstyled">
                <li><a href="{% url 'blog:person_detail' author.slug %}">{{ author.full_name }}</a></li>
                <li><code><a href="mailto:{{ author.email }}">{{ author.email }}</a></code></li>
                <li>{{ author.get_pronouns_display }}.<a href="https://uwm.edu/lgbtrc/support/gender-pronouns/">*</a></li>
                <hr>
                <li>{{ author.formatted_markdown|safe|truncatewords:50 }}</li>
              </ul>
            {% else %}
              <hr>
              <ul class="list-unstyled">
                <li><a href="{% url 'blog:person_detail' author.slug %}"></a>{{ author.full_name }}</a></li>
                <li><code><a href="mailto:{{ author.email }}">{{ author.email }}</a></code></li>
                <li>{{ author.get_pronouns_display }}.<a href="https://uwm.edu/lgbtrc/support/gender-pronouns/">*</a></li>
                <hr>
              </ul>
            {% endif %}
          {% endfor %}
        </div>
    </div>
  </div>
</div>
{% endblock%}

prof_site/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}

{% if first %}
<div class="row lead-article">
  <div class = "jumbotron post-banner" style = "background-image:url({{first.banner_reduced.url}})">
    <div class="container">
      <div class = "col-md-10 offset-md-1 col-sm-10 offset-sm-1 post-banner-text">
        <h4>{{ first.date }}</h4>
        <hr>
        <h1 class="display-4"><a href="{% url 'blog:post_detail' first.slug %}">{{ first.title }}</a></h1>
        <hr>
        <ul class="list-inline">
        {% for author in first.authors.all %}
          <li class="list-inline-item">
            {% if author.page %}
              <a href="{% url 'blog:person_detail' author.slug %}">{{ author.full_name }}</a>
            {% else %}
              {{ author.full_name }}
            {% endif %}
          </li>
        {% endfor %}
        </ul>
        <p>{{ first.pandoc_process|safe|truncatewords:50 }}</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-7 offset-md-1 col-sm-10 offset-sm-1">
    {% if latest_post_list %}
        {% include page_template %}
    {% else %}
        <p>No posts to display.</p>
    {% endif %}
    </div>
    <div class="sticky-top col-md-3 d-none d-md-block">
    <div id="events-col" class="sticky-top">
        <h2>Upcoming Events</h2>
        <ul class="list-unstyled event-list">
        {% if events %}
            {% for event in events%}
            <li><a href="{% if event.website %}{{ event.website }}{% else %}#{% endif %}"><h5>{{ event.title }}</h5></a></li>
            <li>{% if event.conference %}{{event.conference.conference.name}} {{event.conference.start.year}}, {{event.conference.conference.organizations.all.0}}{% endif %}</li>
            <li>{% for p in event.sponsors.all %} <a href="{{p.website}}">{{ p.name }}</a>{%if not forloop.last%}, {% endif %}{% endfor %}</li>
            <li>{{ event.day }}</li>
            <li><code>{{ event.start|time:"H:i" }}–{{ event.end|time:"H:i" }}</code></li>
            <hr>
            {% endfor %}
        {% else %}
        <li>No upcoming events.</li>
        {% endif %}
        </ul>
    </div>
    </div>
</div>
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{{ STATIC_URL }}/static/el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 2500
        });</script>
{% endblock %}

{% endblock%}

prof_site/blog/templates/blog/post_list_page.html
{% load el_pagination_tags %}

{% paginate latest_post_list %}
{% for post in latest_post_list %}
<div class="row article">
  <div class = "card-back">
    <div class = "col-md-12">
      <h5>{{ post.date }}</h5>
      <h2 class="display-6">
        <a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a>
      </h2>
      <ul class="list-inline">
        {% for author in post.authors.all %}
        <li class="list-inline-item">
          {% if author.page %}
            <a href="{% url 'blog:person_detail' author.slug %}">{{ author.full_name }}</a>
          {% else %}
            {{ author.full_name }}
          {% endif %}
        </li>
        {% endfor %}
      </ul>
      <img src="{{post.banner_reduced.url}}" />
      <p>{{ post.pandoc_process|safe|truncatewords:50 }}</p>
      <hr class="article-break">
    </div>
  </div>
</div>
{% endfor %}
{% show_more %}

prof_site/blog/templates/blog/vita.html
{% extends "blog/base.html" %}
{% block content %}

{% for e in education %}
{{e}}
{% endfor %}

{% endblock %}